# yaml-language-server: $schema=https://raw.githubusercontent.com/octo-sts/app/refs/heads/main/pkg/octosts/octosts.TrustPolicy.json

issuer: ${{ secrets.GH_LAMBDA_ISSUER }}
subject: ${{ secrets.GH_LAMBDA_SUBJECT }}

permissions:
  actions: write
